// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9SGHDnaelRijEJ2OzCaib-5oII1ihITY',
    appId: '1:1082249763792:web:90c240db614d763bd337d5',
    messagingSenderId: '1082249763792',
    projectId: 'waterpotability-23eb7',
    authDomain: 'waterpotability-23eb7.firebaseapp.com',
    storageBucket: 'waterpotability-23eb7.firebasestorage.app',
    measurementId: 'G-CHX8FJ28WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ6jl-3CHeO6TlEMCwyWVi1MOX-b6TDwA',
    appId: '1:1082249763792:android:73621d8d779f38dad337d5',
    messagingSenderId: '1082249763792',
    projectId: 'waterpotability-23eb7',
    storageBucket: 'waterpotability-23eb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZf6EvylNRRGHP11qGmbQwn5EfBVLfoQQ',
    appId: '1:1082249763792:ios:f4c470f57d901a22d337d5',
    messagingSenderId: '1082249763792',
    projectId: 'waterpotability-23eb7',
    storageBucket: 'waterpotability-23eb7.firebasestorage.app',
    iosBundleId: 'com.example.waterQuality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZf6EvylNRRGHP11qGmbQwn5EfBVLfoQQ',
    appId: '1:1082249763792:ios:f4c470f57d901a22d337d5',
    messagingSenderId: '1082249763792',
    projectId: 'waterpotability-23eb7',
    storageBucket: 'waterpotability-23eb7.firebasestorage.app',
    iosBundleId: 'com.example.waterQuality',
  );
}
